server:
  port: 8082

spring:
  application:
    name: saga-orchestrator

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

    consumer:
      group-id: saga-orchestrator-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.sagaorchestrator.event"
        spring.json.use.type.headers: false
#        spring.json.value.default.type: com.example.sagaorchestrator.event.OrderCreatedEvent

logging:
  level:
    org.apache.kafka: WARN
    com.example.sagaorchestrator: DEBUG

outbox:
  poll:
    interval-ms: 2000   # как часто опрашивать таблицу
    batch-size: 100     # сколько записей забирать за один цикл