server:
  port: 8485

spring:
  application:
    name: saga-orchestrator

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

    consumer:
      group-id: saga-orchestrator-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.sagaorchestrator.event"
        spring.json.use.type.headers: false
#        spring.json.value.default.type: com.example.sagaorchestrator.event.OrderCreatedEvent

logging:
  level:
    org.apache.kafka: WARN
    com.example.sagaorchestrator: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

outbox:
  dlq:
    move-interval-ms: 300000
  poll:
    interval-ms: 2000
    batch-size: 100
    max-attempts: 5
    base-backoff-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: saga-orchestrator