package com.example.sagaorchestrator.entity;

public enum SagaStep {
    ORDER_CREATED,
    PAYMENT_PROCESSING,
    PAYMENT_COMPLETED,
    INVENTORY_PROCESSING,
    INVENTORY_COMPLETED,
    INVENTORY_FAILED,
    REFUNDING_PAYMENT,
    PAYMENT_REFUNDED,
    CANCELLING_ORDER,
    ORDER_CANCELLED,
    SHIPPING_STARTED,
    COMPLETED
}
